name: Compile Script
on:
  push:
  pull_request:

jobs:
  lint-and-compile:
    strategy:
      matrix:
        include:
          - os: windows-2022
            name: Windows
            path: dist\nativegen.exe
          - os: ubuntu-22.04
            name: Ubuntu
            path: ./dist/nativegen
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.9"
          cache: pip
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Build Executable
        run: pyinstaller --onefile --distpath dist --workpath build --clean --icon NONE --name nativegen nativegen.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: NativeGen-${{ matrix.name }}
          path: ${{ matrix.path }}
          if-no-files-found: error
